config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get '/', to: "users#index"
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :destroy], param: :post_id 
  end

  resources :posts, only: [:show], param: :post_id 
  resources :posts, only: [], param: :post_id do
    member do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:create]
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :read, :all
      can :create, Post
      can :create, Comment
      can :create, Like

      can :destroy, Post do |post|
        post.AuthorId_id == user.id
      end
      can :destroy, Comment do |comment|
        comment.AuthorId_id == user.id
      end

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.model.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'
  belongs_to :post, foreign_key: 'PostId_id'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'
  belongs_to :post, foreign_key: 'PostId_id'

  validates :text, :AuthorId_id, :PostId_id, presence: true

  after_save do
    post.increment!(:Comments_Counter)
  end
end

app/models/like.model.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'
  belongs_to :post, foreign_key: 'PostId_id'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'
  belongs_to :post, foreign_key: 'PostId_id'

  validates :AuthorId_id, :PostId_id, presence: true

  after_save do
    post.increment!(:Likes_Counter)
  end
end

app/models/post.model.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'

  has_many :comments, dependent: :destroy, foreign_key: 'PostId_id'
  has_many :likes, dependent: :destroy, foreign_key: 'PostId_id'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'AuthorId_id'

  has_many :comments, dependent: :destroy, foreign_key: 'PostId_id'
  has_many :likes, dependent: :destroy, foreign_key: 'PostId_id'

  validates :Text, :AuthorId_id, presence: true
  validates :Title, length: { in: 1..250 }, presence: true, allow_blank: false
  validates_numericality_of :Comments_Counter, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :Likes_Counter, only_integer: true, greater_than_or_equal_to: 0

  after_save do
    author.increment!(:Posts_Counter)
  end

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.model.rb
class User < ApplicationRecord
  has_many :comments, foreign_key: 'AuthorId_id', dependent: :destroy
  has_many :posts, foreign_key: 'AuthorId_id', dependent: :destroy
  has_many :likes, foreign_key: 'AuthorId_id', dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: 'AuthorId_id', dependent: :destroy
  has_many :posts, foreign_key: 'AuthorId_id', dependent: :destroy
  has_many :likes, foreign_key: 'AuthorId_id', dependent: :destroy

  validates :Name, presence: true
  validates_numericality_of :Posts_Counter, only_integer: true, greater_than_or_equal_to: 0

  def three_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:Name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(text: comment_params[:Text], AuthorId_id: current_user.id, PostId_id: @post.id)

    if @comment.save
      redirect_to "/posts/#{@post.id}", notice: 'Comment Added!'
    else
      redirect_to "/posts/#{@post.id}", alert: 'Error occured, Comment Not Saved!'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = @comment.post
    @post.decrement!(:Comments_Counter)
    @comment.destroy!
    redirect_to "/posts/#{@post.id}", notice: 'Comment Deleted!'
  end

  private

  def comment_params
    params.permit(:Text, :post_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.new(AuthorId_id: current_user.id, PostId_id: @post.id)

    if @like.save
      flash[:notice] = 'Like created succsefully'
      redirect_to "/posts/#{@post.id}", notice: 'Like Added!'
    else
      flash[:alert] = 'Liking failed.'
      redirect_to "/posts/#{@post.id}", alert: 'Error occured, Like Not Saved!'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
    @current_user = @user
  end

  def show
    @post = Post.includes(:comments).find(params[:post_id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])

    new_post = @user.posts.new(post_params)
    new_post.Likes_Counter = 0
    new_post.Comments_Counter = 0
    respond_to do |format|
      format.html do
        if new_post.save
          redirect_to user_posts_path(params[:user_id]), notice: 'Post was successfully created.'
        else
          render :new, alert: 'Error occurred, please try again. Post not saved'
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    user = User.find(post.AuthorId_id)
    user.Posts_Counter -= 1
    post.destroy
    user.save
    flash[:alert] = 'You have successfully deleted the post!'
    redirect_to user_posts_path(post.AuthorId_id)
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.includes(:posts).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "sessions/new", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <% if user_signed_in? %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts/show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "posts/new", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
  <%= link_to current_user.email, edit_user_registration_path %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Register", new_user_registration_path %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users/show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "users/index", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <% if user_signed_in? %>
  <%= link_to current_user.email, edit_user_registration_path %>
  <%= button_to "Log out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Log in", new_user_session_path %>
  <%= link_to "Register", new_user_registration_path %>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<body>
  <nav>
    <h1 class="text-center m-2"> Ruby Blog App </h1>
  </nav>

  <main>
    <section class="container my-4">
      <div class="row">
        <div class="col col-3">
          <img src="https://dummyimage.com/250/9f9ede/000000" class="img-fluid profile-picture" alt="user profile picture">
        </div>
        <div class="col col-9 border">
          <div class="grid-username-container">
            <p class="username-header text-center"> <%= @user.Name %> </p>
            <p class="number-of-posts"> Number of Posts : <%= @user.Posts_Counter%> </p>
          </div>
        </div>
        </div>
    </section>

    <button type="button" class="btn btn-light mx-auto d-block my-2"> <%= link_to "Create Post", controller: "posts", action: "new" %> </button>
    <% if @posts.blank? %>
        <p class="text-center">There are not any posts currently in the system for this user.</p>
    <% else %>
      <% @posts.each do |post| %>
        <section class="container my-4 px-0">
          <div class="border post-container p-4">
            <p> <%= link_to post.Title, {:action => 'show', :post_id => post.id} %> </p>
            <p>
              <%= post.Text %> 
            </p>
            <div>
                <% if can? :destroy, post %> 
                  <%= button_to "Delete Post", destroy_user_session_path, method: :delete %>
                <% end %>
                <p class="comment-like-text text-end"> Comments: <%= post.Comments_Counter %>, Likes: <%= post.Likes_Counter %> </p>
            </div>
            <div class="border comment-container p-2">
              <% if post.five_recent_comments.blank? %>
                <p> No comments on this post </p>
              <% else %>
                <% post.five_recent_comments.each do |comment| %>
                  <p> <%= comment.author.Name %> : <%= comment.text %></p>
                <% end %>
              <% end %>
            </div>
          </div>
        </section>
      <% end %>
    <% end %>

    <div class="container see-more-post-container my-2">
      <button type="button"  class="see-all-posts-button btn btn-lg"> Pagination </button>
    </div>
  </main>
</body>

app/views/posts/new.html.erb
<h1 class="text-center my-2"> Create New Post</h1>

<%= form_with(model: @post, url:user_posts_path) do |form| %>
  <%= form.label :Title, "Input Your Post Title" %>
  <%= form.text_field :Title %>
  <%= form.label :Text, "Input Your Post Content" %>
  <%= form.text_area :Text, size: "60x10" %>
  <%= form.submit "Create"%>
<% end %>

app/views/posts/show.html.erb
<section class="container my-4 px-0">
      <div class="border post-container p-4">
        <div class="post-comment-container">
          <p class="h4"> <%= @post.Title %> by <%= @post.author.Name %> </p>
          <p class="comment-like-text text-end"> Comments: <%= @post.Comments_Counter %>, Likes: <%= @post.Likes_Counter %> </p>
          <%= form_with model: @like, url: likes_path do |f|%>
            <%= f.submit "Like This Post" , data: { disable_with: "Loading..."} , class: "likes-btn" %>
          <%end%>
        </div>
        <p>
          <%= @post.Text %> 
        </p>
        <div class="border comment-container p-2">
          <% if @post.comments.blank? %>
              <p class="text-center"> No comments on this post </p>
          <% else %>
             <% @post.comments.each do |comment| %>
                <div class="comment-text">
                  <div class="comment-grid">
                    <p class="my-auto"> <%= comment.author.Name %> : <%= comment.text %></p>
                    <% if can? :destroy, comment %> 
                      <%= button_to "Delete Comment", comment_path(id: comment.id), method: :delete  %>
                    <% end %>
                  </div>
                </div>
             <% end %>
          <% end %>
        </div>

        <div>
          <p class="h3 text-center my-2"> Create New Comment </p>
          <%= form_with model: @comment, url: comments_path do |form| %>
            <%= form.label :Text, "Input Your Post Content" %>
            <%= form.text_area :Text, size: "60x10" %>
            <%= form.submit "Create"%>
          <% end %>
        </div>
      </div>
    </section> 

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
  <body>
    <nav>
      <h1 class="text-center m-2"> Ruby Blog App</h1>
    </nav>

    <main>
      <% if @users.blank? %>
        <p>There are not any posts currently in the system.</p>
      <% else %>
        <% @users.each do |user| %>
          <section class="container my-4">
            <div class="row">
              <div class="col col-3">
                <img src="https://dummyimage.com/250/9f9ede/000000" class="img-fluid profile-picture" alt="user profile picture">
              </div>
              <a href="/users/<%= user.id %>" class="col col-8 user-profile-link">
                <div class="username-text-container border text-center align-middle m-1">
                  <p class="user-name-text"> <%= user.Name %> </p>
                  <p class="posts-counter-text"> Number of Posts: <%= user.Posts_Counter %>  </p>
                </div>
              </a>
            </div>
          </section>
        <% end %>
      <% end %>
    </main>

  </body>
</html> 

app/views/users/show.html.erb
<body>
  <nav>
    <h1 class="text-center m-2"> Ruby Blog App </h1>
  </nav>

  <main>
    <section class="container my-4">
      <div class="row">
        <div class="col col-3">
          <img src="https://dummyimage.com/250/9f9ede/000000" class="img-fluid user-profile-picture" alt="user profile picture">
        </div>
        <div class="col col-9 border">
          <div class="grid-username-container">
            <p class="username-header text-center"> <%= @user.Name %> </p>
            <p class="number-of-posts"> Number of Posts: <%= @user.Posts_Counter %> </p>
          </div>
        </div>
        </div>
    </section>
      <section class="container my-4 px-0">
        <div class="border bio-container p-4">
        <p> Bio </p>
        <p> <%= @user.Bio %></p>
        </div>
    </section>

    <% if @user.three_recent_posts.blank? %>
        <p class="text-center">There are not any posts currently in the system for this user.</p>
    <% else %>
      <% @user.three_recent_posts.each do |post| %>
        <section class="container my-4 px-0">
          <a href="/posts/<%= post.id %>">
            <div class="border post-container p-4">
              <p> <%= post.Title %> </p>
              <p>
                <%= post.Text %>
              </p>
              <div>
                <% if can? :destroy, post %> 
                  <%= button_to "Delete Post", {:controller => "posts", :action => "destroy", :user_id => @user.id, :post_id => post.id }, method: :delete  %>
                <% end %>
                <p class="comment-like-text text-end"> Comments: <%= post.Comments_Counter %>, Likes: <%= post.Likes_Counter %> </p>
              </div>
            </div>
          </a>
        </section>
      <% end %>
    <% end %>

    <div class="container see-more-post-container my-2">
      <a href= "<%= @user.id %>/posts" class="see-all-posts-button">
        <button type="button"  class="btn btn-lg see-all-posts-btn"> See all posts </button>\
      </a>
    </div>
  </main>
</body>